var cuestionario = new Array();

cuestionario[0] = ["¿Cuál es el la primera etapa del desarrollo de software de cualquier tipo?",1,["El diseño.","La implementación","Las pruebas.","La arquitectura."]];
cuestionario[1] = ["¿Cuál es el objetivo del diseñador de Software?",1,["Producir un modelo o representación de una entidad que será construida más adelante., manejo y mantenimiento del sistema. ","Producir un modelo o representación de una entidad que no será construida más adelante.","Producir modelos de software rápidamente.","Producir modelos de software efectivamente."]];
cuestionario[2] = ["¿Cuál es teóricamente la parte más importante de la ingeniería de software?",3,["La implementación.","Las pruebas.","El diseño.","La arquitectura."]];
cuestionario[3] = ["¿Por qué es necesario dedicarle al diseño el tiempo suficiente para su correcta realización?",2,["Porque es la primera parte de la ingeniería de software.", "Porque es la parte más importante de la ingeniería de software.","Producir un modelo o representación de una entidad que será construida más adelante.","Producir un modelo o representación de una entidad que no será construida más adelante."]];
cuestionario[4] = ["Existen diferentes notaciones y lenguajes para la notación del diseño de software:",4,["Para representar la estructura.","Representar el comportamiento.","Algunas se emplean principalmente en el contexto de métodos específicos.","Para representar la estructura, representar el comportamiento y algunas se emplean principalmente en el contexto de métodos específicos."]];
cuestionario[5] = ["¿En qué se basan casi todas las notaciones para el diseño de software?",2,["En la programación funcional.","En el Lenguaje de Modelado Unificado (UML).","En el lenguaje de programación Java.","En el paradigma de programación orientado a objetos."]];
cuestionario[6] = ["¿Qué es el modelado de sistemas?",4,["Es el proceso para desarrollar software abstracto.","Es el proceso para desarrollar diseños abstractos de un sistema.","Es el proceso para desarrollar sistemas abstractos.","Es el proceso para desarrollar modelos abstractos de un sistema."]];
cuestionario[7] = ["¿Qué presenta cada parte del modelado de sistemas?",1,["Una visión o perspectiva diferente del sistema.","Una visión o perspectiva igual del sistema.","Una visión o perspectiva equivalente del sistema.","Una visión o perspectiva parecida del sistema."]];
cuestionario[8] = ["¿En qué se ha convertido el modelado de sistemas?",2,["El modelado de sistemas se ha convertido en un medio para representar alguna notación gráfica.","El modelado de sistemas se ha convertido en un medio para representar el sistema usando algún tipo de notación gráfica.","En algún tipo de notación gráfica.","El modelado de sistemas se ha convertido en un medio para representar muchas notaciones gráficas."]];
cuestionario[9] = ["¿Para cuál o cuáles sistemas es posible desarrollar modelos?",2,["Para ningún sistema.","Para el sistema existente y el del sistema a diseñar.","Para el sistema existente.","Para el sistema a diseñar."]];
cuestionario[10] = ["¿Cuándo se usan los modelos del sistema existentes?",4,["Se usan durante todos los procesos.","Se usan durante el proceso de diseño del nuevo sistema.","Se usan durante el proceso de pruebas del nuevo sistema.","Se usan durante el proceso de requerimientos del nuevo sistema."]];
cuestionario[11] = ["¿Cuándo se usan los modelos del sistema nuevo?",4,["Se usan durante todos los procesos.","Se usan durante el proceso de diseño del nuevo sistema.","Se usan durante el proceso de pruebas del nuevo sistema." ,"Se usan durante el proceso de requerimientos del nuevo sistema."]];
cuestionario[12] = ["¿Para qué usan los ingenieros los modelos de sistemas nuevos?",3,["Para todo el proceso del desarrollo de software.","Para discutir las propuestas de diseño de software.","Para discutir las propuestas de diseño y documentar el sistema para la implementación.","Para discutir como documentar el sistema."]];
cuestionario[13] = ["¿Cuál es el aspecto más importante de un modelo del sistema?",1,["Es que deja fuera los detalles.","Es que contiene algunos los detalles.","Es que contiene todos los detalles.","Es la primera etapa del desarrollo de software."]];
cuestionario[14] = ["¿Qué es un modelo?",1,["Es una abstracción del sistema a estudiar.","Es representación alternativa de dicho sistema.","Es algún tipo de notación gráfica.","Es la primera etapa del desarrollo de software."]];
cuestionario[15] = ["¿Qué no es un modelo?",2,["Es una abstracción del sistema a estudiar","Es representación alternativa de dicho sistema.","Es algún tipo de notación gráfica.","Es la primera etapa del desarrollo de software."]];
cuestionario[16] = ["¿Qué debe mantener la representación de un sistema?",1,["Toda la información sobre la entidad a representar.","Alguna parte de la información sobre la entidad a representar.","El diseño del sistema existente.","El diseño del nuevo sistema."]];
cuestionario[17] = ["¿Cómo debe ser la abstracción de un sistema?",4,["Completo y debe recoger deliberadamente las características más destacadas.","Simplificado y debe recoger todas las características.","Completo y debe recoger todas las características.","Simplificado y debe recoger deliberadamente las características más destacadas."]];
cuestionario[18] = ["¿Cuándo se desarrollen modelos de sistema hay que ser flexibles con la notación gráfica?",2,["No, siempre necesitará apegarse rigurosamente a los detalles técnicos de una notación.","No siempre necesitará apegarse rigurosamente a los detalles técnicos de una notación.","Sí siempre necesitará apegarse rigurosamente a los detalles técnicos de una notación.","Nunca necesitará apegarse rigurosamente a los detalles técnicos de una notación."]];
cuestionario[19] = ["¿Cuál es el propósito del modelo de software? ",3,["Ser una abstracción del sistema a estudiar.","Ser una representación alternativa de dicho sistema.","Estimular la discusión entre los ingenieros de software que intervienen en el desarrollo del sistema.","Terminar la discusión entre los ingenieros de software que intervienen en el desarrollo del sistema."]];
cuestionario[20] = ["¿Cuándo pueden los modelos ser incompletos? ",1,["Cuando cubran los puntos clave de la discusión.","Cuando algunos de los puntos clave de la discusión.","Cuando terminen la discusión entre los ingenieros de software que intervienen en el desarrollo del sistema.","Nunca, siempre se debe apegar a la notación técnica."]];
cuestionario[21] = ["¿Cuándo se puede utilizar de manera informal la notación de modelado?",3,["Cuando algunos de los puntos clave de la discusión.","Cuando terminen la discusión entre los ingenieros de software que intervienen en el desarrollo del sistema.","Cuando cubran los puntos clave de la discusión.","Nunca, siempre se debe apegar a la notación técnica."]];
cuestionario[22] = ["¿Deben estar completos los modelos cuando se usan para documentar un producto de software?",1,["No tienen que estar completos ya que puede que sólo desee desarrollar modelos para algunos módulos del sistema.","Sí tienen que estar completos ya que puede que sólo desee desarrollar modelos para algunos módulos del sistema.","No importa ya que puede que sólo desee desarrollar modelos para algunos módulos del sistema.","Deben tener la notación técnica correcta."]];
cuestionario[23] = ["Cuando no están completos los modelos al momento de documentar un producto de software, ¿cómo deben ser?",1,["Deben ser correctos ya que tienen que usar adecuadamente la notación y ser una descripción precisa del sistema.","Deben estar completos ya que tienen que usar adecuadamente la notación y ser una descripción precisa del sistema.","Deben ser una descripción precisa del sistema.","Deben ser una descripción abstracta del sistema."]];
cuestionario[24] = ["¿Qué proporciona UML?",3,["Un pequeño conjunto de diagramas que se usan en pequeños subconjuntos para poder representar un sistema.","Un modelo del sistema existente.","Un amplio conjunto de diagramas que se usan en pequeños subconjuntos para poder representar un sistema.","Un modelo del nuevo sistema."]];
cuestionario[25] = ["¿Para qué se utilizan los diagramas de UML?",2,["Para la implementación del software.","Para representar diferentes perspectivas de un sistema.","Para dar una descripción precisa del sistema.","Para dar una descripción abstracta del sistema."]];
cuestionario[26] = ["¿Cuál de estas afirmaciones sobre UML son correctas?",1,["Es el lenguaje de modelado de sistemas de software más conocido y utilizado en la actualidad.","Es el lenguaje de modelado de sistemas de software menos conocido y más utilizado en la actualidad.","Es el lenguaje de modelado de sistemas de software más conocido y menos utilizado en la actualidad.","Es el lenguaje de modelado de sistemas de software menos conocido y menos utilizado en la actualidad."]];
cuestionario[27] = ["¿Qué quieren decir las siglas UML?",3,["Lenguaje unico de modelado (Unique Modeling Language).","Lenguaje unificado de modelo (Unified Model Language).","Lenguaje unificado de modelado (Unified Modeling Language).","Lenguaje indefinido de modelado (Undefined Modeling Language)."]];
cuestionario[28] = ["¿Quién respalda a la UML?",4,["OG (Object Group).","OM (Object Management).","OMWG (Object Management Work Group).","OMG (Object Management Group)."]];
cuestionario[29] = ["¿Qué es UML?",1,["Es un lenguaje gráfico para visualizar, especificar, construir y documentar un sistema.","Es un lenguaje de etiquetas.","Es un lenguaje de programación estructurado.","Es un lenguaje de programación orientado a objetos."]];

cuestionario[30] = ["¿Qué son los modelos de comportamiento?",1,["Son modelos dinámicos del sistema conforme se ejecuta.","Son modelos estáticos del sistema conforme se ejecuta.","Son modelos dinámicos y estáticos del sistema conforme se ejecuta.","Son modelos del sistema."]];
cuestionario[31] = ["¿Qué se muestra en los modelos de comportamiento?",1,["En ellos se muestra lo que sucede o lo que se supone que pasa cuando un sistema responde ante un estímulo de su entorno.","En ellos se muestra lo que sucede o lo que se supone que pasa cuando un sistema responde ante un estímulo interno.","La instancia de los objetos.","Los objetos."]];
cuestionario[32] = ["¿A qué tipos de estímulos responden los modelos de comportamiento?",1,["Datos y eventos.","Datos.","Eventos.","Ningún tipo de estímulo."]];
cuestionario[33] = ["¿Qué describe un caso de uso?",4,["Un grupo de actividades de un sistema que produce un resultado correcto.","Actividad de un sistema que produce un resultado correcto y tangible.","Actividades de un sistema que produce un resultado correcto tangible.","Un grupo de actividades de un sistema que produce un resultado correcto y tangible."]];
cuestionario[34] = ["¿Qué son los casos de uso?",2,["Los casos de uso son descriptores de las interacciones típicas entre los usuarios de un sistema y el hardware.","Los casos de uso son descriptores de las interacciones típicas entre los usuarios de un sistema y el sistema.","Los casos de uso son descriptores de modelos.","Los casos de uso son descriptores de software."]];
cuestionario[35] = ["¿Qué es un actor en los casos de uso?",4,["Es una entidad interna.","Es una entidad externa.","Es una entidad interna que interacciona con el sistema participando en un caso de uso.","Es una entidad externa que interacciona con el sistema participando en un caso de uso."]];
cuestionario[36] = ["¿Cómo se representan a los actores en los casos de uso?",1,["Con un hombre de palos.","Con un diamante.","Con un cuadrado.","Con un círculo."]];
cuestionario[37] = ["¿Qué debo hacer si deseo especificar diferentes variantes del mismo caso de uso?",2,["Se puede incluir una relación entre dos casos de uso de tipo “include”.","Se puede incluir una relación entre dos casos de uso de tipo “extend”.","Se puede incluir una relación entre dos casos de uso de una generalización.","Se puede incluir una relación entre dos casos de uso de herencia."]];
cuestionario[38] = ["¿Qué es un diagrama de robustez?",4,["Es una representación del comportamiento descrito por un caso de uso.","Es una representación gráfica del comportamiento descrito por un diagrama de clases.","Es una representación gráfica del comportamiento descrito por un actor.","Es una representación gráfica del comportamiento descrito por un caso de uso."]];
cuestionario[39] = ["¿Qué muestran los diagramas de secuencia?",4,["Los diagramas de secuencia muestran la forma en que un grupo de objetos se comunican entre sí a lo largo del sistema.","Los diagramas de secuencia muestran la forma en que un grupo de objetos se comunican entre sí en el software.","Los diagramas de secuencia muestran la forma en que un grupo de objetos se comunican entre sí en el hardware.","Los diagramas de secuencia muestran la forma en que un grupo de objetos se comunican entre sí a lo largo del tiempo."]];

var nums = [0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39];
var pr1 = Math.floor(Math.random() * (10+1));
var currentIndex = nums.length, temporaryValue, randomIndex ;

while (0 !== currentIndex) {
	randomIndex = Math.floor(Math.random() * currentIndex);
	currentIndex -= 1;

	temporaryValue = nums[currentIndex];
	nums[currentIndex] = nums[randomIndex];
	nums[randomIndex] = temporaryValue;
}
