var cuestionario = new Array();

cuestionario[0] = ["¿Cómo se clasifican los requerimentos?",3,["Estrategicos y funcionales.","Relacionales y no relacionales.","Funcionales y no funcionales.","Afuncionales y disfuncionales."]];
cuestionario[1] = ["Son tres clasificaciones de requerimentos funcionales: ",2,["Estrategicos y funcionales.","Interfaz,Datos y Transaccionales","Funcionales y no funcionales.","Eficiencia, funcionalidad y amabilidad."]];
cuestionario[2] = ["Son tres clasificaciones de requerimentos no funcionales: ",4,["Estrategicos y funcionales.","Interfaz,Datos y Transaccionales","Funcionales y no funcionales.","Eficiencia, funcionalidad y amabilidad."]];
cuestionario[3] = ["Estándar en el que se basan para definir los requerimentos no funcionales: ",3,["ISO-9000","Estandar jerarquíco","Estándar ISO/IEC 9125","Norma ISO 25000"]];
cuestionario[4] = ["¿A qué se refiere la portabilidad?",4,["Al software sin errores","A un programa malicioso","A la capacidad del software de ser transmitido de un entorno a otro.","A que un sistema pueda ser eficaz."]];
cuestionario[5] = ["¿Qué buscan los requerimentos de interfaz?",1,["Determinar la forma en cómo los usuarios van a interactuar con el sistema","El numero de usuarios que soporta el sistema","Que el tipo de información se adecuado al sistema","Mostrar un buen desempeño."]];
cuestionario[6] = ["¿Qué define la funcionalidad?",4,["Que el sistema trabaja con un paradigma funcional.","Que el sistema es una función.","Que el sistema debe estar en función del objetivo.","Características para alcanzar el funcionamiento deseado del sistema."]];
cuestionario[7] = ["¿Cómo es llamada la Amabilidad del sistema en algunas ocasiones?",2,["Generosidad","Usabilidad","Eficiencia","Gentileza"]];
cuestionario[8] = ["La confiabilidad es: ",3,["Confiar en el cliente.","Seguridad de mi sistema.","Capacidad del sistema para mantener niveles de rendimiento bajo ciertas condiciones y un tiempo de respuesta dado.","Cpacidad de confiar en que el cliente dará los requerimentos correctos"]];
cuestionario[9] = ["¿Qué es la seguridad del sistema?",2,["Que cargue rápido.","Capacidad del software para cumplir con los niveles de riesgo permitidos ante posibles daños físicos del sistema como para riesgo de datos.","Capacidad para tener un respaldo de datos","Que el sistema sea portable."]];
cuestionario[10] = ["¿Qué definen los requerimentos funcionales?",1,["La capacidad que tendrá el sistema que se desarrollará, describiendo procesos, que llevan a la transformación de las entradas para obtener salidas deseadas.","Que el sistema sea 100% funcional.","La capacidad del sistema para trabajar con un paradigma funcional.","Que importa la funcionalidad."]];
cuestionario[11] = ["¿Qué definen los requerimentos no funcionales?",4,["Que el sistema no soporta paradigma funcional","Que el sistema no es una funcion","Que el sistema no depende de nada.","Las posibles causas que son limitantes del sistema."]];
cuestionario[12] = ["¿Qué resulta del análisis de requerimentos?",3,["Un sistema confiable.","Un sistema eficiente.","La especificación de las características operativas del software","Las posibles causas que son limitantes del sistema."]];
cuestionario[13] = ["Son tipos de modelos: ",2,["Modelo relacional,imperativo y declarativo.","Modelo de datos, orientados al flujo y de comportamiento.","Modelo cliente servidor, modelo transaccional y funcional.","Modelo OSI."]];
cuestionario[14] = ["¿Qué dan los modelos al diseñador de software?",1,["La información que se traduce en  en diseños de arquitectura, interfaz, y componentes.","Un diseño óptimo.","Heramientas para trabajar.","Las posibles causas que son limitantes del sistema."]];
cuestionario[15] = ["¿Qué ilustra el modelo de datos?",4,["Que el sistema no soporta paradigma funcional","Que el sistema no es una funcion","Que el sistema no depende de nada.","Las posibles causas que son limitantes del sistema."]];
cuestionario[16] = ["¿Qué factores se toman en cuenta para la documentación?",4,["El factor tiempo.","El FPS.","El factor eficiencia y eficacia.","Formatos de documentos y métodos de acceso."]];
cuestionario[17] = ["¿A qué se refieren los formatos de los documentos según su tipología y métodos de acceso?",1,["Aquí se definen los formatos y plantillas elegidos para los diagramas de diseño,hojas de cálculo y hojas de seguimiento de proyecto.","Que el sistema no falle.","Que el sistema funcione bien y sin errores.","Las posibles causas que son limitantes del sistema."]];
cuestionario[18] = ["¿A qué se refiere el método de acceso y flujo de trabajo de cada tipo de documento?",3,["A quien será el administrador del sistema.","A la jerarquía de usuarios.","A quién va a tener acceso a los diferentes tipos de documentos y bajo qué privilegios. ","Las posibles causas que son limitantes del sistema."]];
cuestionario[19] = ["¿Qué es la gestión de requerimentos?",2,["Es el análisis de los requerimentos.","Es el proceso de comprender y controlar los cambios en los requerimientos del sistema.","Es el proceso de documentar los requerimentos de un proyecto de software.","Son aquellos que nos permite regular los requerimentos."]];
cuestionario[20] = ["Es el objetivo de un analista: ",3,["Análizar y gestionar los requerimentos.","Programar el backend.","Reconocer los elementos básicos de un sistema tal como lo percibe el usuario o cliente.","Reconocer los errores en un sistema."]];
cuestionario[21] = ["¿Con quién debe establecer contacto un analista?",1,["Con el equipo técnico y de gestión del cliente y con la empresa que vaya a desarrollar el software.","Con el contador.","Con el abogado.","Con el jefe de proyecto."]];
cuestionario[22] = ["¿Cuándo surgen nuevas necesidades en el sistema para los usuarios?",2,["Cuando lo estan planeando.","Cuando no funciona.","Cuando el programador se los dice.","Cuando tienen experiencia con un sistema."]];
cuestionario[23] = ["Pueden entrar en conflicto: ",3,["Requerimentos funcionales y no funcionales.","Modelos de diseño.","Requerimientos debido a las restricciones organizacionales y de presupuesto.","Analista y diseñador."]];
cuestionario[24] = ["Es otro motivo por el que cambian los requerimentos: ",1,["El entorno de negocios y técnico del sistema cambian después de la instalación","El entorno de negocios y técnico del sistema no sirven.","El entorno de negocios y técnico del sistema no hicieron lo solicitado","El entorno de negocios no funcionó."]];
cuestionario[25] = ["¿Cuándo debe empezar el proceso de gestión de requerimientos?",4,["Cuando esté disponible una versión final del sistema.","Cuando esté disponible una versión alfa del sistema.","Cuando esté disponible una versión beta del sistema.","Cuando esté disponible una versión preliminar del documento de requerimientos"]];
cuestionario[26] = ["Hay que establecer un proceso formal para: ",2,["implantar las soluciones a los errores encontrados durante la depuración.","Implantar las propuestas de cambios y planear como se van a gestionar los requerimientos que cambian durante el proceso de obtención de requerimientos.","implantar los cambios propuestos en los requerimentos.","Firmar el contrato del proyecto."]];
cuestionario[27] = ["Desde una perspectiva evolutiva, los requerimientos se dividen en dos clases: ",1,["Requerimentos duraderos y volátiles.","Requerimentos funcionales y no funcionales.","Requerimentos dentro y fuera del tiempo.","Requerimentos síncronos y asíncronos."]];
cuestionario[28] = ["¿A qué se refieren los requerimentos duraderos?",4,["Al tiempo que durará el sistema.","A la fecha en que el sistema dejará de ser útil.","A la duración del sistema en años.","A la relación directamente con la actividad principal de la organización."]];
cuestionario[29] = ["¿A qué se refieren los requerimentos volátiles?",3,["Cambian antes el proceso de desarrollo o después de que éste se haya puesto en funcionamiento.","Cambian siempre el proceso de desarrollo y después de que éste se haya puesto en funcionamiento.","Cambian durante el proceso de desarrollo o después de que éste se haya puesto en funcionamiento.","Cambian después el proceso de desarrollo."]];
cuestionario[30] = ["Es la ventaja de utilizar un proceso formal: ",1,["Todos los cambios propuestos son tratados de forma consistente y que los cambios en el documento de requerimientos se hacen de forma controlada.","Ningún cambio propuesto es tratado de forma consistente y que los cambios en el documento de requerimientos se hacen de forma controlada.","Algunos de los cambios propuestos son tratados de forma inconsistente y que los cambios en el documento de requerimientos se hacen de forma controlada.","Algunos de los cambios propuestos son tratados de forma inconsistente y que los cambios en el documento de requerimientos se hacen de forma descontrolada."]];
cuestionario[31] = ["¿Cómo empieza un proceso formal?",4,["Con la identificación de un error en los requerimientos funcionales.","Con la identificación de un problema en los requerimientos no funcionales.","Con la identificación de los requerimientos funcionales.","Con la identificación de un problema en los requerimientos."]];
cuestionario[32] = ["¿Cómo debe organizarse el documento de requerimentos?",2,["Haciendo sus secciones tan modulares como sea posible, de tal modo que se puedan hacer cambios en él sin tener que hacer grandes reorganizaciones.","Haciendo que sus secciones no sean modulares.","Haciendo que sus secciones no sean modulares, de tal modo que se no  se puedan hacer cambios en él.","Reorganizar todo el documento incluyendo cambio de requerimentos."]];
cuestionario[33] = ["¿A qué conduce la tentación de agregar cambios a los requerimentos?",4,["A que la especificación de requerimientos y la implementación del sistema provoquen errores.","A que la especificación de requerimientos y la implementación del sistema se retrasen.","A que la especificación de requerimientos y la implementación del sistema se junten.","A que la especificación de requerimientos y la implementación del sistema se desfasen."]];
cuestionario[34] = ["¿Qué es un requerimento?",1,["Una característica que debe tener el sistema o una restricción que debe satisfacer para que sea aceptado por el cliente.","Una característica que no debe tener el sistema o una restricción que debe satisfacer para que sea aceptado por el cliente.","Un tipo de error en un proyecto de software.","Un tipo de dato."]];
cuestionario[35] = ["¿Qué pretende definir la ingeniería de requerimentos?",4,["Los requerimientos del sistema que se está construyendo.","Los métodos de ordenamiento del sistema que se está construyendo.","La arquitectura del sistema que se está construyendo.","El diseño del sistema que se está construyendo."]];
cuestionario[36] = ["Actividades de la ingeniería de requerimentos: ",1,["Análisis y obtención de requerimentos.","Metodología e integración de requerimentos.","Contratar al diseñador y analista para el sistema.","Aplicar el cambio de requerimentos y errores."]];
cuestionario[37] = ["¿A qué da resultado la obtención de requerimentos?",3,["Una especificación del sistema que el cliente comprende.","Una especificación del sistema que el cliente no comprende.","Un nuevo tipo de dato para el sistema que el cliente comprende.","Un nuevo tipo de dato para el sistema que el cliente no comprende."]];
cuestionario[38] = ["¿A qué da resultado el análisis de requerimentos?",1,["Un modelo de análisis que los desarrolladores pueden interpretar sin ambigüedad","Un modelo ambigüo para los programadores.","Un modelo básico de desarrollo.","Los pasos para un buen diseño."]];
cuestionario[39] = ["¿Qué requiere la obtención de requerimentos?",2,["Conocer al cliente.","La colaboración de varios grupos de participantes con diferentes niveles de conocimientos. ","Saber los problemas más comúnes.","Saber preguntar al cliente."]];
cuestionario[40] = ["¿Qué son los requerimentos de navegación?",4,["Aquellos que incluyen un GPS.","Aquellos que te pueden localizar por tu IP.","Aquellos que sirven para navegar en internet,","Aquellos que deeterminan la forma en que los usuarios van a navegar o a desplazarse dentro del sistema."]];
cuestionario[41] = ["¿Qué es la satisfacción?",3,["Sentirse bien con uno mismo.","Sentirse bien con los demás.","Capacidad del software de cumplir con las expectativas de los usuarios en un contexto determinado. ","Capacidad del software de no cumplir con las expectativas de los usuarios en un contexto determinado. "]];
cuestionario[42] = ["Clasificación de los requerimentos de eficiencia: ",1,["Requerimentos de rendimiento y requerimentos de espacio.","Requerimentos de seguridad.","Requerimentos de privacidad.","Requerimentos éticos."]];
cuestionario[43] = ["Clasificación de los requerimentos legislativos: ",2,["Requerimentos de rendimiento y requerimentos de espacio.","Requerimentos de seguridad y privacidad.","Requerimentos de privacidad.","Requerimentos éticos."]];
cuestionario[44] = ["Clasificación de los requerimentos de eficiencia: ",4,["Requerimentos de rendimiento y requerimentos de espacio.","Requerimentos de seguridad.","Requerimentos de privacidad.","Requerimentos éticos e interoperabilidad."]];
cuestionario[45] = ["Orden de los pasos para la comprensión de las necesidades del usuario: ",1,["Comprensión del problema,requerimentos iniciales,cambio en la comprensión del problema,requerimentos cambiados.","Cambio en la comprensión del problema,comprensión del problema,requerimentos iniciales,requerimentos cambiados.","Requerimentos cambiados,comprensión del problema,requerimentos iniciales,cambio en la comprensión del problema.","Requerimentos iniciales,comprensión del problema,requerimentos cambiados,cambio en la comprensión del problema."]];
cuestionario[46] = ["¿A qué se refiere la capacidad de mantenimiento?",3,["A realizar cambios dentro de su estructura sin perder funcionalidad","A no realizar cambios dentro de su estructura sin perder funcionalidad","A aceptar cambios dentro de su estructura sin perder funcionalidad.","A no aceptar cambios dentro de su estructura sin perder funcionalidad"]];
cuestionario[47] = ["Clasificación de requerimentos organizacionales: ",4,["Requerimentos funcionales y no funcionales.","Requerimentos de seguridad y privacidad.","Requerimentos éticos.","Requerimentos de entrega,implementación y estándares."]];
cuestionario[48] = ["¿En que se enfocan los requerimentos organizacionales?",1,["En la observancia de las políticas y procedimientos de la organización, así como de las de los desarrolladores. ","En la seguridad y privacidad del proyecto.","En los valores éticos del personal de la empresa.","En las técnicas utilizadas en la toma de requerimentos."]];
cuestionario[49] = ["Incluye a todos los factores externos del sistema y del proceso de desarrollo: ",2,["Requerimentos de seguridad.","Requerimentos externos.","Requerimentos éticos.","Requerimentos de privacidad."]];

var nums = [0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49];
var pr1 = Math.floor(Math.random() * (10)+1);
var currentIndex = nums.length, temporaryValue, randomIndex ;

while (0 !== currentIndex) {
	randomIndex = Math.floor(Math.random() * currentIndex);
	currentIndex -= 1;

	temporaryValue = nums[currentIndex];
	nums[currentIndex] = nums[randomIndex];
	nums[randomIndex] = temporaryValue;
}
