var cuestionario = new Array();
//Combinatorias
cuestionario[0] = ["¿Cuántos números de 5 cifras diferentes se puede formar con los dígitos: 1, 2, 3, 4, 5.?",3,["0","5","120","404"]];
cuestionario[1] = ["¿De cuántas formas distintas pueden sentarse ocho personas en una fila de butacas?",2,["2","40320","403203","0"]];
cuestionario[2] = ["¿De cuántas formas distintas pueden sentarse ocho personas alrededor de una mesa redonda?",4,["10","34","5300","5040"]];
cuestionario[3] = ["Con las letras de la palabra libro, ¿cuántas ordenaciones distintas se pueden hacer que empiecen por vocal?",3,["84","100","48","2500"]];
cuestionario[4] = ["¿Cuántos números de cinco cifras distintas se pueden formar con las cifras impares? ¿Cuántos de ellos son mayores de 70.000?",4,["98","987","5","48"]];
cuestionario[5] = ["En una clase de 35 alumnos se quiere elegir un comité formado por tres alumnos. ¿Cuántos comités diferentes se pueden formar?",1,["6545","6540","7654","0"]];
cuestionario[6] = ["¿De cuántas formas pueden mezclarse los siete colores del arco iris tomándolos de tres en tres?",4,["53","90","87","35"]];
cuestionario[7] = ["¿A una reunión asisten 10 personas y se intercambian saludos entre todos. ¿Cuántos saludos se han intercambiado?",2,["Ninguno","45","56","54"]];
cuestionario[8] = ["¿Cuántas apuestas de Lotería Primitiva de una columna han de rellenarse para asegurarse el acierto de los seis resultados, de 49?",2,["9876","13983816","99876","345675"]];
cuestionario[9] = ["Demuestre que si 8 personas están en una habitación, al menos dos de ellas cumplen años el mismo día de la semana.",1,["Las palomas son las personas y los nidos son los días de la semana. Como hay 8 palomas y 7 nidos, hay algún nido con más de una paloma, es decir, hay algún día de la semana en el cual cumplen años dos (o más) de esas personas.","Las palomas son las personas y los nidos son los días de la semana. Como hay 7 palomas y 6 nidos, hay algún nido con más de una paloma, es decir, hay algún día de la semana en el cual cumplen años dos (o más) de esas personas.","Las palomas son las personas y los nidos son los días de la semana. Como hay 4 palomas y 2 nidos, hay algún nido con más de una paloma, es decir, hay algún día de la semana en el cual cumplen años dos (o más) de esas personas.","No se puede resolver."]];
cuestionario[10] = ["Si una persona puede tener no más de 200.000 cabellos, ¿es posible que en una ciudad de 300.000 habitantes haya dos personas con la misma cantidad de cabellos en la cabeza?",4,["Si, es seguro que existen dos personas con la misma cantidad de cabellos. Las palomas son las 200.000 personas y los nidos son las cantidades de cabellos (0,1,2,...,300.000). A cada paloma le corresponde uno de esos nidos. Como hay más palomas que nidos, hay algún nido (cantidad) con más de una paloma (habitante).","No existen personas con la misma cantidad de cabellos.","No se puede resolver","Si, es seguro que existen dos personas con la misma cantidad de cabellos. Las palomas son las 300.000 personas y los nidos son las cantidades de cabellos (0,1,2,...,200.000). A cada paloma le corresponde uno de esos nidos. Como hay más palomas que nidos, hay algún nido (cantidad) con más de una paloma (habitante)."]];
//Palomar
cuestionario[11] = ["Dibujamos en el plano un hexágono regular de lado 3 metros, y pintamos en su interior o en su frontera 2009 puntos rojos distintos. Demuestra que hay un triángulo equilátero de lado 1 metro, incluido en el interior o la frontera del anterior, en cuyo interior o frontera hay al menos 38 puntos rojos distintos. ",3,["No hay demostración","No podemos dividir el hexágono regular ","podemos dividir el hexágono regular en tres triángulos equiláteros de lado 3 metros, dibujando sus diagonales mayores. Cada uno de estos triángulos puede ser a su vez dividido en 9 triángulos equiláteros de lado 1 metro, dividiendo primero cada lado en tres segmentos iguales, y luego dibujando por cada uno de los puntos de división líneas paralelas a los lados del triángulo (¡prueba tú mismo a hacer el dibujo!). Tenemos así el hexágono dividido en 54 triángulos equiláteros de lado 1 metro, de forma que los interiores y las fronteras de estos triángulos cubren completamente el interior y la frontera del hexágono. Como 2009=54×37+11, y cada punto rojo, al estar en el hexágono, está en uno de los 54 triángulos, entonces por el principio del palomar hay al menos uno de los triángulos que contiene al menos 38 puntos. ","No se puede resolver."]];
cuestionario[12] = ["Dibujamos en el plano un hexágono regular de lado 3 metros, y pintamos en su interior o en su frontera 2009 puntos rojos distintos. Demuestra que hay un triángulo equilátero de lado 1 metro, incluido en el interior o la frontera del anterior, en cuyo interior o frontera hay al menos 38 puntos rojos distintos. ",3,["No hay demostración","No podemos dividir el hexágono regular ","podemos dividir el hexágono regular en tres triángulos equiláteros de lado 3 metros, dibujando sus diagonales mayores. Cada uno de estos triángulos puede ser a su vez dividido en 9 triángulos equiláteros de lado 1 metro, dividiendo primero cada lado en tres segmentos iguales, y luego dibujando por cada uno de los puntos de división líneas paralelas a los lados del triángulo (¡prueba tú mismo a hacer el dibujo!). Tenemos así el hexágono dividido en 54 triángulos equiláteros de lado 1 metro, de forma que los interiores y las fronteras de estos triángulos cubren completamente el interior y la frontera del hexágono. Como 2009=54×37+11, y cada punto rojo, al estar en el hexágono, está en uno de los 54 triángulos, entonces por el principio del palomar hay al menos uno de los triángulos que contiene al menos 38 puntos. ","No se puede resolver."]];
cuestionario[13] = ["En una escuela hay 367 alumnos. Demuestra que al menos dos de ellos cumplen años el mismo día.",3,["Exactamente tres cumplen el mismo día.","Ninguno cumple el mismo día.","Al menos dos cumplen el mismo día.","Sólo uno cumple el mismo día."]];
cuestionario[14] = ["En una escuela hay 367 alumnos. Demuestra que al menos dos de ellos cumplen años el mismo día.",3,["Exactamente tres cumplen el mismo día.","Ninguno cumple el mismo día.","Al menos dos cumplen el mismo día.","Sólo uno cumple el mismo día."]];
cuestionario[15] = ["Se sabe que el número de pelos de la cabeza de cualquier hombre es menor que 200000. Prueba que en la CDMX hay al menos dos mexicanos con el mismo número de pelos en la cabeza.",2,["Al menos dos tienen el mismo numero de pelos.","Exactamente dos tienen el mismo número de pelos.","Sólo uno tiene el mismo número de pelos.","Ninguno tiene el mismo número de pelos."]];
cuestionario[16] = ["Un cuadrado de 5 por 5 se divide en 25 cuadrados de 1 por 1. Probar que si se pintan 26 puntos sobre el cuadrado grande al menos hay un cuadrado pequeño en el que se han pintado dos puntos.",2,["Ninguna casilla esta ocupada por dos puntos.","Al menos una casilla esta ocupada por dos puntos.","Todas estan ocupadas por dos puntos.","No hay solución."]];
cuestionario[17] = ["Probar que entre 101 puntos de un cuadrado de lado 10 cm hay al menos dos puntos que distan entre si menos de 2 cm: ",3,["Dividiendo el cuadrado en 100 cuadrados de lado 1, al menos un cuadrado contiene dos puntos. La distancia entre dos puntos en un cuadrado de lado 1 es menor o igual que √2,por tanto menor que 2.","Dividiendo el cuadrado en 50 cuadrados de lado 1, al menos un cuadrado contiene dos puntos. La distancia entre dos puntos en un cuadrado de lado 1 es menor o igual que √2,por tanto menor que 2.","Dividiendo el cuadrado en 200 cuadrados de lado 1, al menos un cuadrado contiene dos puntos. La distancia entre dos puntos en un cuadrado de lado 1 es menor o igual que √2,por tanto menor que 2.","Dividiendo el cuadrado en 20 cuadrados de lado 1, al menos un cuadrado contiene dos puntos. La distancia entre dos puntos en un cuadrado de lado 1 es menor o igual que √2,por tanto menor que 2."]];

//Relaciones
cuestionario[18] = ['Resuelve la siguiente relación de concurrencia: <br><img src="./img/rr1.png"> ',1,["an = 6 · 2^n − 2 · n · 2^n","an = 2 · 2^n − 3 · n · 2^n","an = 3 · 2^n − 2 · n · 2^n","an = 6 · 2^n − 2 · n · 3^n"]];
cuestionario[19] = ['Resuelve la siguiente relación de concurrencia: <br><img src="./img/rr2.png"> ',3,["an = (−3) · n","an = 2 + (−3) · n","an = 4 + (−3) · n","an = 4 + (−2) · n"]];
cuestionario[20] = ['Resuelve la siguiente relación de concurrencia: <br><img src="./img/rr3.png"> ',4,["an = A · 3n + 8B · 2n","an = A · 3n + B · n","an = A · n + B · 2n","an = A · 3n + B · 2n"]];
cuestionario[21] = ['Resuelve la siguiente relación de concurrencia: <br><img src="./img/rr4.png"> ',2,["an = A · 1^n + B · 2^n + B · 2^n = A + B · 3^n + C · 3^n","an = A · 1^n + B · 2^n + B · 3^n = A + B · 2^n + C · 3^n","an = A · 1^n + B · 2^n + B · 3^n = A + B · 3^n + C · 1^n","an = A · 1^n + B · 1^n + B · 1^n = A + B · 1^n + C · 3^n"]];
cuestionario[22] = ['Resuelve la siguiente relación de concurrencia: <br><img src="./img/rr5.png"> ',4,["an = A · 2^n + B · 3^n","an = 5A · 5^n + B · 1^n","an = A · 1^n + B · 2^n","an = A · 5^n + B · 2^n"]];

//Teoría
cuestionario[23] = ["¿En qué se basa la teoría de conteo?",1,["En técnicas que nos proporcionan información de todas las maneras posibles en que ocurre un determinado evento.","En técnicas que no proporcionan información de todas las maneras posibles en que ocurre un determinado evento","En técnicas como el abaco, y la regla de cálculo.","En técnicas antigüas cuya aplicación es compleja y difícil de entender."]];
cuestionario[24] = ["¿Qué es un diagrama de árbol?",3,["Un árbol binario.","Un diagrama utilizado para la eficiencia de un problema.","Es una herramienta utilizada para determinar todos los posibles resultados de un experimento aleatorio","Es una herramienta para calcular la media."]];
cuestionario[25] = ["¿Qué significa permutar?",2,["Que permite realizar la operación de multiplicación.","Variar la disposición u orden en que estaban dos o más cosas","Que no permite variar la disposición u orden en que estaban dos o más cosas","Que suma la disposición u orden en que estaban dos o más cosas"]];
cuestionario[26] = ["Un conjunto se diferencie de los demás en, al menos, un elemento: ",2,["Combinaciones con repetición.","Combinaciones sin repetición.","Permutaciones con repetición.","Permutaciones sin repetición"]];
cuestionario[27] = ["Una agrupación se diferencie de las demás en, al menos, un elemento: ",1,["Combinaciones con repetición.","Combinaciones sin repetición.","Permutaciones con repetición.","Permutaciones sin repetición"]];
cuestionario[28] = ["¿Qué significa combinar?",2,["Separar los elementos de un conjunto.","Unir cosas diversas, de manera que formen un compuesto","La interseccion de los elementos de un conjunto.","Mezclar los elementos sin importar su tipo."]];
cuestionario[29] = ["En cada grupo entren los n elementos y que un grupo se diferencie de los demás en el orden de colocación de los elementos: ",4,["Combinaciones con repetición.","Combinaciones sin repetición.","Permutaciones con repetición.","Permutaciones sin repetición"]];
cuestionario[30] = ["Cada una de las configuraciones se diferencie de las demás en el orden de colocación de sus elementos, excluyendo las reordenaciones de elementos indistinguibles: ",3,["Combinaciones con repetición.","Combinaciones sin repetición.","Permutaciones con repetición.","Permutaciones sin repetición"]];
cuestionario[31] = ["¿Con qué otro nombre se conoce el teorema de Pigeonhole?",2,["Teorema del pollino","Teorema de palomar","Teorema de paps","Teorema de grafos."]];
cuestionario[32] = ["¿Qué son las funciones generadoras?",1,["Son una  técnica de gran utilidad a la hora de resolver problemas de distribuciones con restricciones. ","Son una técnica para aplicar teoría de grafos","Son una técnica para aplicar el teorema de palomar."," Son una técnica de gran utilidad a la hora de resolver problemas de distribuciones sin restricciones. "]];
cuestionario[33] = ["¿Qué es una relación de concurrencia?",1,["Es una ecuación que relaciona an con ciertos predecesores ","Es una ecuación que no relaciona an con ciertos predecesores ","Es una ecuación no lineal","Es una ecucación cuadrática."]];
cuestionario[34] = ["¿Qué indica el éxito del principio de palomar?",4,["Que no existe solución para el ejercicio.","Que el ejercicio se puede resolver.","Que no existe el objeto.","Que existe el objeto."]];
cuestionario[35] = ["Fórmula para permutaciones con repetición: ",4,['<img src="./img/comb1.png">','<img src="./img/comb2.png">','<img src="./img/fg1.png">','<img src="./img/per2.png">']];
cuestionario[36] = ["Otro nombre del teorema de Drichlet: ",3,["Principio de la vaca.","Principio del arenero.","Principio de la caja de zapatos.","Principio de la ballena."]];
cuestionario[37] = ["No dice como encontrar el objeto ni cuántos objetos hay: ",2,["Teoría de conteo.","Principio de Drichlet.","Función generadora.","Relación de concurrencia."]];
cuestionario[38] = ["Asegura que la nueva configuración sea en esencia distinta a la antigua: ",3,["Combinaciones.","Diagrama de árbol.","Permutaciones.","Principio de palomar."]];
cuestionario[39] = ["Combinaciones, permutaciones y diagrama de árbol estan incluídas en: ",1,["Teoría de conteo.","Principio de Drichlet.","Función generadora.","Relación de concurrencia."]];


var nums = [0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39];
var pr1 = Math.floor(Math.random() * (10)+1);
var currentIndex = nums.length, temporaryValue, randomIndex ;

while (0 !== currentIndex) {
	randomIndex = Math.floor(Math.random() * currentIndex);
	currentIndex -= 1;

	temporaryValue = nums[currentIndex];
	nums[currentIndex] = nums[randomIndex];
	nums[randomIndex] = temporaryValue;
}
